# render.yaml
services:
  - name: backend
    type: web
    env: docker
    dockerfilePath: ./MyDotnetBackend/Dockerfile
    buildCommand: dotnet publish -c Release -o /app/build
    plan: free # or "starter" depending on your usage
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:80
    healthCheckPath: /health

  - name: frontend
    type: web
    env: docker
    dockerfilePath: ./frontend/Dockerfile # Ensure path to Dockerfile is correct
    buildCommand: npm install && npm run build
    startCommand: nginx -g 'daemon off;'
    buildContext: ./frontend # Make sure the build context is correct
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
