# render.yaml

services:
  - name: backend
    type: web
    env: docker
    dockerfilePath: ./MyDotnetBackend/Dockerfile
    buildCommand: dotnet publish -c Release -o /app/build
    startCommand: dotnet /app/build/MyDotnetBackend.dll
    plan: free  # or "starter" depending on your usage
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:80
    healthCheckPath: /health
    ports:
      - 80  # Backend listens on port 80

  - name: frontend
    type: web
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free  # or "starter" depending on your usage
    envVars:
      - key: NODE_ENV
        value: production
    dependsOn:
      - backend  # Waits for the backend to be deployed first
    healthCheckPath: /
    ports:
      - 80  # Frontend listens on port 80
